eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8773
spring:
  application:
    name: order
##mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.197.103:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: root


