server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false # 关闭自我保护模式

spring:
  application:
    name: eureka1


