
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8771/eureka/,http://localhost:8781/eureka/
spring:
  application:
    name: client
server:
  port: 8762



